# Array Indexing using loop

In [6]:
import numpy as np


In [23]:
arr = linspace (0,5,6)
arr

array([0., 1., 2., 3., 4., 5.])

In [32]:
for data in arr:
    print(data , end=" , ")

0.0 , 1.0 , 2.0 , 3.0 , 4.0 , 5.0 , 

In [33]:
for i in range(len(arr)):
    print(arr[i] , end=" , ")

0.0 , 1.0 , 2.0 , 3.0 , 4.0 , 5.0 , 

In [34]:
print(arr[3:5])

[3. 4.]


In [35]:
print(arr[3:])

[3. 4. 5.]


In [38]:
print(arr[:5])

[0. 1. 2. 3. 4.]
