In [ ]:
 import numpy as np
from numpy import *

#Array Decleration
arr = array([2,3,4,5,6,7])
print(arr)

#Array Decleration with type
arr = array([2,3,5,6.6])
print(arr)
print(arr.dtype)

#Array Decleration and change datatype
arr = array([2,3,5,7.3,8.3] , int)
print(arr)
print(arr.dtype)


arr = linspace(0,5,3)   # arr = linspace(start , end , parts) ; Default parts shows 50
print(arr)
print(arr.dtype)

arr = arange(0,10,2)    #arr = arange(start , end , parts)   ; Default parts shows 1
print(arr);
print(arr.dtype)

arr = logspace(1,10,4)   #arr = logspace(start , end , parts)   ; Default parts shows 50
print(arr)
print(arr.dtype)

arr = zeros((5,3,2),int)
print(arr)


#### Array Creation using List

In [32]:

list = [4,5,2,9,3,5]
arr = np.array(list)
print(arr)

list = ([2,4,5,7,8] , [1,5,6,9,2])
arr = np.array(list)
arr


[4 5 2 9 3 5]


array([[2, 4, 5, 7, 8],
       [1, 5, 6, 9, 2]])

#### Array Creation Uisng Matrix

In [25]:
import numpy as np

matrix = np.full(4,10) #General Matrix Creation
matrix

matrix = np.full((4,3) ,10)
matrix


array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [24]:
matrix = np.eye(3)  #Identity Matrix
matrix


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
matrix = np.diag([4,5,7,9])
matrix

array([[4, 0, 0, 0],
       [0, 5, 0, 0],
       [0, 0, 7, 0],
       [0, 0, 0, 9]])