# Array Selection in Numpy

In [28]:
import numpy as np
from numpy import *

In [29]:
arr = np.random.randint(5,20,(4,6))
arr

array([[12,  6,  5, 16,  7,  7],
       [17, 12,  7,  7, 16, 16],
       [ 5, 14,  5,  6,  9,  6],
       [ 6, 12, 12,  6, 19,  6]])

#### Select a random part form this arr

In [30]:
arr1 = arr[1:3 , 3:6]
arr1

array([[ 7, 16, 16],
       [ 6,  9,  6]])

In [31]:
arr3 = arr[1: , :2]
arr3

array([[17, 12],
       [ 5, 14],
       [ 6, 12]])

In [32]:
arr2 = arr*2
arr2

array([[24, 12, 10, 32, 14, 14],
       [34, 24, 14, 14, 32, 32],
       [10, 28, 10, 12, 18, 12],
       [12, 24, 24, 12, 38, 12]])

In [33]:
arr+arr+arr

array([[36, 18, 15, 48, 21, 21],
       [51, 36, 21, 21, 48, 48],
       [15, 42, 15, 18, 27, 18],
       [18, 36, 36, 18, 57, 18]])

In [34]:
arr-(2*arr2)

array([[-36, -18, -15, -48, -21, -21],
       [-51, -36, -21, -21, -48, -48],
       [-15, -42, -15, -18, -27, -18],
       [-18, -36, -36, -18, -57, -18]])

In [35]:
boolean_array = arr>9
boolean_array

array([[ True, False, False,  True, False, False],
       [ True,  True, False, False,  True,  True],
       [False,  True, False, False, False, False],
       [False,  True,  True, False,  True, False]])