# Most used functions in Numpy

In [4]:
import numpy as np
from numpy import *

In [17]:
arr = arange(2,10,2)
print(arr1)

[2 4 6 8]


In [15]:
mat = np.diag([3,4,5,6])
mat

array([[3, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 6]])

In [18]:
arr.ndim

1

In [19]:
mat.ndim

2

In [23]:
arr.size

4

In [24]:
mat.size

16

In [26]:
arr.shape

(4,)

In [28]:
mat.shape

(4, 4)

In [31]:
mat.reshape(2,8)  # To Chage a two dimension array we use reshape function 

array([[3, 0, 0, 0, 0, 4, 0, 0],
       [0, 0, 5, 0, 0, 0, 0, 6]])

In [40]:
arr2 = mat.ravel()  # To convert a two dimension array into a one dimension array
arr2

array([3, 0, 0, 0, 0, 4, 0, 0, 0, 0, 5, 0, 0, 0, 0, 6])