# Random Generation in Numpy

In [5]:
import numpy as np

arr = np.random.rand(5)    # one dimentional random number array
arr

array([0.04469664, 0.66734069, 0.53336633, 0.4149595 , 0.40632369])

In [16]:
arr = np.random.rand(2,3)  # two dimentional random number array
arr

array([[0.88121794, 0.51685257, 0.10622925],
       [0.81847607, 0.72292536, 0.03151609]])

In [19]:
arr = np.random.rand(2,3,4) # three dimetional array
arr

array([[[0.79377002, 0.02077787, 0.2560827 , 0.35207158],
        [0.69393383, 0.39082877, 0.41974227, 0.46985774],
        [0.82484852, 0.63673604, 0.26481186, 0.89989971]],

       [[0.94998188, 0.39436265, 0.47502113, 0.59533742],
        [0.78532657, 0.73194888, 0.51588076, 0.78698574],
        [0.5641698 , 0.68639621, 0.39420117, 0.69186706]]])

In [21]:
arr = np.random.randn(5)
arr

array([-0.11818526,  0.5874054 ,  1.3561388 , -1.56626561,  0.73587285])

In [24]:
arr = np.random.randint(2,10,5)  # From 2 to 10 we get 5 random number as an one dimentional array
arr

array([8, 4, 8, 9, 2])

In [25]:
arr = np.random.randint(2,10,(3,4)) # from 2 to 10 we get an two dimentional array where the digits are random
arr

array([[9, 7, 3, 6],
       [8, 2, 9, 2],
       [7, 6, 4, 3]])